---
title: "Test notebook useful for testing things"
author: "Jacopo Zacchigna"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    # toc_float: false
    code_fold: hide # Hidden by default unless specified otherwise
    df_print: paged
    highlight: tango
    theme: cosmo
    number_sections: true
    toc_collapsible: true  # Enable collapsible TOC
  word_document:
    toc: true
    toc_depth: '3'
  pdf_document:
    toc: true
    toc_depth: 3
editor_options:
  markdown:
    wrap: 72
---

## Environment Setup 

```{r, echo=F}
## Install requirements
# install.packages("ggplot2")
# install.packages("GGally")
# install.packages("reshape2")
# install.packages("corrplot")
# install ...
# install.packages("pROC")

# Inputation methods
# install.packages("mice")
# Other alternative
# install.packages("VIM") # (Visualization and Imputation of Missing Values) 
```

```{r, echo=T, class.source = 'fold-show'}
## Load requirements 
library(ggplot2)
suppressMessages(library(GGally))
suppressMessages(library(pROC))
suppressMessages(library(corrplot))
library(reshape2)
library(mice)
library(VIM)
library(RColorBrewer)

# Load utilities
source("../src/synthetic_data.R") 
source("../src/missing_data.R") 
source("../src/utils.R") 

# Set seed 
set.seed(42)
```

### Missing data functions

Showcase Introduce Mar function (example to show how to use print_function)

```{r eval=TRUE, echo=FALSE, results='asis'}
print_function_code(introduce_mcar)
```

```{r eval=TRUE, echo=FALSE, results='asis'}
print_function_code(plot_missing_data)
```

# Data Generation and Exploration

## Synthetic Dataset Creation

```{r, echo=T, class.source = 'fold-show'}
# This will create:
# - 5 continuous variables
# - 3 categorical variables with 3, 4, and 5 levels respectively
data <- generate_random_data(n_samples = 1000, 
                           n_continuous = 5, 
                           n_categorical = 3,
                           n_categories = c(3, 4, 5))

# Visualize dataset properties
summary(data)
```
