name: Render R Markdown

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  render_document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown", "ggplot2", "ggExtra", "GGally", "reshape2", "corrplot", "here", "pROC", "randomForest", "mgcv", "rpart", "mice", "missMethods", "VIM", "RColorBrewer", "nord", "transport", "philentropy", "gridExtra", "MASS", "norm", "plotly"))'

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Render R Markdown
        run: |
          R -e 'rmarkdown::render("notebooks/final_results.Rmd", output_format = "html_document")'
